# Stage 1: Build the React application
FROM node:20 as builder

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY . .

RUN npm install

ARG VITE_CRYPTO_KEY
ARG VITE_BACKEND_URL
ARG VITE_URI_INTRA

RUN npm run build

# Stage 2: Set up Nginx and copy the built application
FROM nginx:1.27.2

COPY ./nginx-setup.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /etc/nginx/ssl
RUN openssl req -x509 -newkey rsa:4096 -keyout /etc/nginx/ssl/key.pem -out /etc/nginx/ssl/cert.pem -sha256 -days 3650 -nodes -subj "/C=/ST=/L=/O=/OU=/CN="

COPY --from=builder /usr/src/app/dist /var/www/react

CMD ["nginx", "-g", "daemon off;"]

