FROM node:20

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

ARG VITE_CRYPTO_KEY
ARG VITE_BACKEND_URL
ARG VITE_URI_INTRA

ENV VITE_CRYPTO_KEY=$VITE_CRYPTO_KEY
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
ENV VITE_URI_INTRA=$VITE_URI_INTRA
RUN npm run build 

CMD ["npm", "run", "preview", "--", "--port", "5173", "--host"]
