# Stage 1: Build the React application
FROM node:20 as builder

RUN  apt-get update && apt-get install -y openssl nginx

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY . .

RUN npm install

ARG VITE_CRYPTO_KEY
ARG VITE_BACKEND_URL
ARG VITE_URI_INTRA

# RUN npm run build

COPY ./nginx-setup.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /etc/nginx/ssl
RUN openssl req -x509 -newkey rsa:4096 -keyout /etc/nginx/ssl/key.pem -out /etc/nginx/ssl/cert.pem -sha256 -days 3650 -nodes -subj "/C=/ST=/L=/O=/OU=/CN="

# COPY  /usr/src/app/dist /var/www/react

CMD ["nginx", "-g", "daemon off;"]

