services:
  frontend:
    container_name: frontend
    build: ./Frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend/src:/usr/src/app/src
    restart: always
  backend:
    container_name: backend
    environment:
      - pym="python manager.py"
    build: ./Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/usr/src/app
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - 5432:5432
    volumes:
      - ./database/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "db"]
    restart: always
  
  redis:
    container_name: redis
    image: redis:7
    restart: always
