FROM python:3.12

RUN apt-get update && apt-get install -y netcat-openbsd build-essential libpq-dev


ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


WORKDIR /usr/src/app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .


EXPOSE 8000

CMD ["bash", "script.sh"]
