# Generated by Django 5.1 on 2024-09-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinegamemodel',
            old_name='final_winner',
            new_name='winner',
        ),
        migrations.AlterField(
            model_name='onlinegamemodel',
            name='game_end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='onlinegamemodel',
            name='game_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
