# Generated by Django 5.1 on 2024-08-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinegamemodel',
            old_name='final_winner',
            new_name='winner',
        ),
    ]
