# Generated by Django 5.1 on 2024-09-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_cover_image_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='game_type',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
